import { useState } from "react";
import type { BodyZone, UserThermalLabel, ZoneDecision } from "../domain/thermal.js";
import type { DemoExperience } from "./demo-experience.js";
import { userFacingPreference, ZONE_LABELS } from "./body-map.js";

export type DemoTab = "tonight" | "morning" | "validation";
export type SensorDemoMode = "normal" | "degraded";

export function TopNav({ active, onChange }: { active: DemoTab; onChange: (tab: DemoTab) => void }) {
  const tabs: readonly [DemoTab, string][] = [["tonight", "今晚"], ["morning", "早晨反馈"], ["validation", "技术验证"]];
  return <header className="top-nav topbar"><button className="top-nav__brand" onClick={() => onChange("tonight")}><img className="titie-logo-mark" src="/assets/titie-logo-lockup.svg" alt="体贴，知冷暖，好好睡。"/></button><nav className="tabs" aria-label="主要页面">{tabs.map(([id, label]) => <button key={id} aria-current={active === id ? "page" : undefined} onClick={() => onChange(id)}>{label}</button>)}</nav></header>;
}

export function BodyZoneMarker({ decision, selected, onSelect }: { decision: ZoneDecision; selected: boolean; onSelect: () => void }) {
  return <button type="button" className={`sleep-zone sleep-zone--${decision.action.toLowerCase()}`} data-zone={decision.zone} aria-pressed={selected} onClick={onSelect}><span>{ZONE_LABELS[decision.zone]}</span><strong>{userFacingPreference(decision)}</strong></button>;
}

export function SleepBodyView({ experience, selectedZone, onSelect, compact = false }: { experience: DemoExperience; selectedZone: BodyZone; onSelect: (zone: BodyZone) => void; compact?: boolean }) {
  return <div className={`sleep-body${compact ? " sleep-body--compact" : ""}`} aria-label="俯视睡眠身体区域"><div className="bed"><span className="sr-only">床</span><div className="pillow"><span>枕头</span></div><div className="duvet"><span>被子</span></div><svg className="sleeper" viewBox="0 0 500 680" role="img" aria-label="侧卧在床上的抽象人体轮廓"><ellipse cx="270" cy="128" rx="52" ry="62"/><path d="M250 185c-55 30-78 99-62 169 14 59 48 90 43 151-3 46-32 88-58 123 27 13 58 8 80-13 34-32 53-76 58-121 7-67-17-114-3-177 10-44 15-92-4-120-14-20-31-24-54-12Z"/><path className="sleeper__line" d="M231 252c45 8 88 35 117 73M292 318c-6 50-3 99 16 141M246 465c36 18 73 38 101 73M228 492c-6 51-24 91-58 126"/></svg>{experience.body.decisions.map((decision) => <BodyZoneMarker key={decision.zone} decision={decision} selected={selectedZone === decision.zone} onSelect={() => onSelect(decision.zone)} />)}</div></div>;
}

function humanAction(decision: ZoneDecision) { return decision.action === "WARM" ? "轻轻暖一下" : decision.action === "COOL" ? "稍微凉一点" : "保持刚刚好"; }

export function TechnicalDetails({ experience, zone }: { experience: DemoExperience; zone: BodyZone }) {
  const decision = experience.body.byZone[zone], technical = experience.technical.byZone[zone], command = experience.control.byZone[zone].command;
  return <details className="technical-details"><summary>查看判断依据</summary><dl><div><dt>confidence</dt><dd>{Math.round(decision.confidence * 100)}%</dd></div><div><dt>sensorQuality</dt><dd>{decision.sensorQuality}</dd></div><div><dt>temp slope</dt><dd>{technical.features.skinTempSlopePerMinute.toFixed(3)} °C/min</dd></div><div><dt>zone-to-body delta</dt><dd>{technical.features.zoneToBodyDelta.toFixed(2)} °C</dd></div><div><dt>similar episodes</dt><dd>{technical.similarEpisodes}</dd></div><div><dt>ControlCommand</dt><dd>{command.direction} · L{command.level} · {command.durationMinutes} min</dd></div><div className="wide"><dt>raw engine reasons</dt><dd>{technical.rawReasons.join(" · ")}</dd></div></dl></details>;
}

export function ZoneDetailDrawer({ experience, zone, mode, onClose, onModeChange }: { experience: DemoExperience; zone: BodyZone; mode: SensorDemoMode; onClose: () => void; onModeChange: (mode: SensorDemoMode) => void }) {
  const degraded = mode === "degraded", decision = degraded ? experience.sensorDegraded.decision : experience.body.byZone[zone], command = degraded ? experience.sensorDegraded.command : experience.control.byZone[zone].command;
  return <aside className="zone-drawer" aria-label={`${ZONE_LABELS[zone]}详情`}><div className="drawer-head"><span>{ZONE_LABELS[zone]}</span><button aria-label="关闭详情" onClick={onClose}>×</button></div>{degraded ? <><h2>先不调整，继续观察</h2><p className="drawer-lead">这里的接触数据暂时不够稳定。</p><div className="quiet-state">拿不准的时候，少做一点。</div></> : <><h2>建议暖一点</h2><ol className="reason-list"><li>最近15分钟，这里的温度在慢慢下降。</li><li>当前状态和过去选择“暖一点”时比较接近。</li><li>房间整体变化不大，所以先不调整整张床。</li></ol><button className="primary-button">{humanAction(decision)}</button><p className="action-meta">约{command.durationMinutes}分钟 · {command.reevaluateAfterMinutes}分钟后再判断</p></>}<button className="demo-switch" onClick={() => onModeChange(degraded ? "normal" : "degraded")}>{degraded ? "恢复稳定接触数据" : "演示接触数据不稳定"}</button>{degraded ? <details className="technical-details"><summary>查看判断依据</summary><dl><div><dt>sensorQuality</dt><dd>{decision.sensorQuality}</dd></div><div><dt>confidence</dt><dd>{Math.round(decision.confidence * 100)}%</dd></div><div><dt>ControlCommand</dt><dd>{command.direction} · L{command.level}</dd></div></dl></details> : <TechnicalDetails experience={experience} zone={zone}/>}</aside>;
}

export function CurrentAdjustment({ experience }: { experience: DemoExperience }) { return <section className="current-adjustment card"><h2>正在调整</h2>{(["knee_leg", "shoulder_back"] as BodyZone[]).map(zone => <div className="adjustment-row" key={zone}><span><strong>{ZONE_LABELS[zone]}</strong>{humanAction(experience.body.byZone[zone])}</span><time>{experience.control.byZone[zone].command.durationMinutes}分钟</time></div>)}<div className="adjustment-row"><span><strong>其他位置</strong>保持刚刚好</span></div><p>5分钟后再判断</p></section>; }
export function NightTimeline({ experience }: { experience: DemoExperience }) { return <section className="night-timeline card"><div><h2>这一晚</h2><p className="principle">拿不准的时候，少做一点。</p></div><ol>{experience.timeline.map(event => <li key={`${event.time}-${event.detail}`}><time>{event.time}</time><span>{event.detail}</span></li>)}</ol></section>; }

export function Tonight({ experience, selectedZone, onSelect, onOpenDrawer }: { experience: DemoExperience; selectedZone: BodyZone; onSelect: (zone: BodyZone) => void; onOpenDrawer: () => void }) {
  return <main><section className="tonight-hero"><div className="night-meta"><span>{experience.tonight.time}</span><span>室温 {experience.tonight.ambientTemp}°C</span><span>湿度 {experience.tonight.ambientHumidity}%</span><span className="prototype-label">{experience.tonight.evidenceLabel}</span></div><div className="hero-grid"><section className="sleep-stage card"><SleepBodyView experience={experience} selectedZone={selectedZone} onSelect={(z) => { onSelect(z); onOpenDrawer(); }}/></section><div className="night-status"><section className="summary card"><p className="eyebrow">今晚状态</p><h1>{experience.body.summary}</h1><p className="status-count">{experience.body.attentionZones.length}个位置需要轻微调整</p><div className="zone-summary">{experience.body.decisions.filter(d => d.action !== "HOLD").map(d => <button key={d.zone} onClick={() => { onSelect(d.zone); onOpenDrawer(); }}><span>{ZONE_LABELS[d.zone]}</span><strong>{d.action === "WARM" ? "建议暖一点" : d.action === "COOL" ? "建议凉一点" : "刚刚好"}</strong></button>)}</div></section><CurrentAdjustment experience={experience}/></div></div></section><NightTimeline experience={experience}/></main>;
}

export function SimilarEpisodeView({ experience, result }: { experience: DemoExperience; result?: ZoneDecision }) { const s=experience.personalization.historySummary, after=result ?? experience.personalization.after; return <section className="similar-episodes"><p className="eyebrow">个人变化</p><h2>不是记住一个答案，而是记住相似的时刻。</h2><p>过去相似的{s.similarEpisodeCount}个夜晚</p><div className="episode-bars"><span>暖一点 <i style={{width:`${s.labelCounts["暖一点"]*20}%`}}/></span><span>刚刚好 <i style={{width:`${s.labelCounts["刚刚好"]*20}%`}}/></span><span>凉一点 <i style={{width:`${s.labelCounts["凉一点"]*20}%`}}/></span></div><div className="before-after"><div><small>反馈前</small><strong>{userFacingPreference(experience.personalization.before)}</strong><span>判断把握 {Math.round(experience.personalization.before.confidence*100)}%</span></div><div><small>反馈后</small><strong>{userFacingPreference(after)}</strong><span>判断把握 {Math.round(after.confidence*100)}%</span></div></div></section>; }

export function MorningFeedback({ experience }: { experience: DemoExperience }) { const [zone,setZone]=useState<BodyZone>("knee_leg"), [label,setLabel]=useState<UserThermalLabel>("暖一点"), [result,setResult]=useState<ZoneDecision>(), [expanded,setExpanded]=useState(false); return <main className="morning-page"><div className="page-intro"><h1>昨晚，有哪里还想调整吗？</h1><p>如果没有，也可以什么都不改。</p></div><div className="morning-grid"><section className="morning-body card"><SleepBodyView compact experience={experience} selectedZone={zone} onSelect={setZone}/></section><section className="feedback-card card"><p>{ZONE_LABELS[zone]}</p><h2>如果再来一次，你希望这里？</h2><div className="feedback-options">{(["暖一点","刚刚好","凉一点"] as UserThermalLabel[]).map(x=><button key={x} aria-pressed={label===x} onClick={()=>setLabel(x)}>{x}</button>)}</div><button className="primary-button" onClick={()=>{setResult(experience.feedback.submitAndRerun(zone,label));setExpanded(true);}}>记住这次选择</button>{result?<div className="remembered"><h3>记住了</h3><p>下次遇到相似状态，会把这次选择考虑进去。</p></div>:null}</section></div>{expanded?<SimilarEpisodeView experience={experience} result={result}/>:null}</main>; }

const strategyCopy = [{id:"fixed-whole-bed",title:"整床恒温",body:"一个地方变化，整张床一起调。",tag:"容易过度调整"},{id:"fixed-zone-threshold",title:"固定分区",body:"知道不同位置，但每个人使用同一阈值。",tag:"不能学习个人差异"},{id:"titie-personalized",title:"体贴",body:"身体区域 + 当晚变化 + 个人历史。",tag:"只调整真正需要的地方"}] as const;
export function TechnicalValidation({ experience }: { experience: DemoExperience }) { const reports=experience.validation.reports, titie=reports.find(x=>x.strategyId==="titie-personalized")!; return <main className="validation-page"><div className="page-intro"><h1>为什么不是一个温度？</h1><p>三种策略运行在完全相同的合成场景与偏好标签上。</p></div><div className="strategy-cards">{strategyCopy.map(s=><article className={`card${s.id === "titie-personalized" ? " featured" : ""}`} key={s.id}><h2>{s.title}</h2><p>{s.body}</p><strong>{s.tag}</strong></article>)}</div><section className="metric-section card"><div><small>和个人偏好一致</small><strong>{(titie.metrics.preferenceMatch.rate*100).toFixed(1)}%</strong></div><div><small>不必要调整</small><strong>{(titie.metrics.unnecessaryIntervention.rate*100).toFixed(1)}%</strong></div><div><small>个人反馈带来的改善</small><strong>+{(titie.personalizationGain*100).toFixed(1)} pp</strong></div></section><details className="full-validation"><summary>查看完整验证</summary>{reports.map(r=><dl key={r.strategyId}><dt>{r.strategyId}</dt><dd>Whole-bed Overcorrection {(r.metrics.wholeBedOvercorrection.rate*100).toFixed(1)}% · Direction Reversal {(r.metrics.directionReversal.rate*100).toFixed(1)}%</dd></dl>)}</details><aside className="simulation-note card"><strong>原型模拟结果</strong><p>用于验证控制策略，不代表真实人体或临床效果。</p></aside></main>; }
